=== endur4ever/pf2e-kingmaker-tools/src/commonMain/resources/schemas/expedition-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/expedition-activity.json",
  "title": "Expedition Activity",
  "description": "An expedition activity",
  "$ref": "#/$defs/ExpeditionActivity",
  "$defs": {
    "ExpeditionActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "isHomebrew",
        "isSecret",
        "isLocked",
        "skills",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ExpeditionSkill"
          }
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "oncePerSession": {
          "type": "boolean"
        }
      }
    },
    "ExpeditionSkill": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "dcType",
        "proficiency"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "proficiency": {
          "type": "string",
          "enum": [
            "untrained",
            "trained",
            "expert",
            "master",
            "legendary"
          ]
        },
        "dc": {
          "type": "number"
        },
        "required": {
          "type": "boolean"
        },
        "dcType": {
          "type": "string",
          "enum": [
            "zone",
            "actorLevel",
            "none",
            "static"
          ]
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/rest.json
{
  "id": "rest",
  "name": "expeditionActivities.rest.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "criticalSuccess": {
    "message": "expeditionActivities.rest.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.rest.success.message"
  },
  "failure": {
    "message": "expeditionActivities.rest.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.rest.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/personal-quest.json
{
  "id": "personal-quest",
  "name": "expeditionActivities.personal-quest.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "any",
      "proficiency": "trained",
      "dcType": "actorLevel",
      "required": true
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.personal-quest.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.personal-quest.success.message"
  },
  "failure": {
    "message": "expeditionActivities.personal-quest.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.personal-quest.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/hunt.json
{
  "id": "hunt",
  "name": "expeditionActivities.hunt.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "survival",
      "proficiency": "trained",
      "dcType": "zone",
      "required": true
    },
    {
      "name": "hunting",
      "proficiency": "trained",
      "dcType": "zone",
      "required": false
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.hunt.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.hunt.success.message"
  },
  "failure": {
    "message": "expeditionActivities.hunt.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.hunt.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/craft.json
{
  "id": "craft",
  "name": "expeditionActivities.craft.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "crafting",
      "proficiency": "trained",
      "dcType": "actorLevel",
      "required": true
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.craft.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.craft.success.message"
  },
  "failure": {
    "message": "expeditionActivities.craft.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.craft.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/treasure-hunt.json
{
  "id": "treasure-hunt",
  "name": "expeditionActivities.treasure-hunt.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "perception",
      "proficiency": "expert",
      "dcType": "zone",
      "required": true
    },
    {
      "name": "thievery",
      "proficiency": "trained",
      "dcType": "zone",
      "required": false
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.treasure-hunt.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.treasure-hunt.success.message"
  },
  "failure": {
    "message": "expeditionActivities.treasure-hunt.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.treasure-hunt.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/diplomacy.json
{
  "id": "diplomacy",
  "name": "expeditionActivities.diplomacy.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "diplomacy",
      "proficiency": "trained",
      "dcType": "actorLevel",
      "required": true
    },
    {
      "name": "society",
      "proficiency": "untrained",
      "dcType": "actorLevel",
      "required": false
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.diplomacy.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.diplomacy.success.message"
  },
  "failure": {
    "message": "expeditionActivities.diplomacy.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.diplomacy.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/scout.json
{
  "id": "scout",
  "name": "expeditionActivities.scout.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "survival",
      "proficiency": "trained",
      "dcType": "zone",
      "required": true
    },
    {
      "name": "perception",
      "proficiency": "trained",
      "dcType": "zone",
      "required": false
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.scout.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.scout.success.message"
  },
  "failure": {
    "message": "expeditionActivities.scout.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.scout.criticalFailure.message"
  },
  "oncePerSession": false
}

=== endur4ever/pf2e-kingmaker-tools/data/expedition-activities/train.json
{
  "id": "train",
  "name": "expeditionActivities.train.name",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "athletics",
      "proficiency": "trained",
      "dcType": "actorLevel",
      "required": true
    }
  ],
  "criticalSuccess": {
    "message": "expeditionActivities.train.criticalSuccess.message"
  },
  "success": {
    "message": "expeditionActivities.train.success.message"
  },
  "failure": {
    "message": "expeditionActivities.train.failure.message"
  },
  "criticalFailure": {
    "message": "expeditionActivities.train.criticalFailure.message"
  },
  "oncePerSession": false
}
