=== endur4ever/pf2e-kingmaker-tools/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Currency": {
      "type": "string",
      "enum": [
        "cp",
        "sp",
        "gp",
        "pp"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "id",
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "isSpecialMeal": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "object",
          "required": [
            "value",
            "currency"
          ],
          "properties": {
            "value": {
              "type": "number"
            },
            "currency": {
              "$ref": "#/$defs/Currency"
            }
          }
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "requirements": {
          "type": "string"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Conditions": {
      "type": "object",
      "required": [
        "condition",
        "value"
      ],
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "drained",
            "enfeebled",
            "stupefied",
            "clumsy"
          ]
        },
        "value": {
          "type": "number"
        },
        "afterRest": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "removeWhenPreparingCampsite": {
          "type": "boolean"
        },
        "removeAfterRest": {
          "type": "boolean"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "changeFatigueDurationSeconds": {
          "type": "number"
        },
        "reduceConditions": {
          "type": "object",
          "mode": {
            "type": "string",
            "enum": [
              "all",
              "random"
            ]
          },
          "drained": {
            "type": "number"
          },
          "stupefied": {
            "type": "number"
          },
          "clumsy": {
            "type": "number"
          },
          "enfeebled": {
            "type": "number"
          },
          "afterRest": {
            "type": "boolean"
          }
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healMode": {
          "type": "string",
          "enum": [
            "afterConsumption",
            "afterRest",
            "afterConsumptionAndRest"
          ]
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        },
        "grantsFreeAction": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "freeAction",
                "singleAction",
                "reaction"
              ]
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "durationSeconds": {
              "type": "number"
            }
          },
          "required": [
            "type",
            "name"
          ]
        },
        "grantsReaction": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": [
                "freeAction",
                "singleAction",
                "reaction"
              ]
            },
            "name": {
              "type": "string"
            },
            "description": {
              "type": "string"
            },
            "durationSeconds": {
              "type": "number"
            }
          },
          "required": [
            "type",
            "name"
          ]
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== endur4ever/pf2e-kingmaker-tools/data/recipes/Grilled Silver Eel.json
{
  "id": "grilled-silver-eel",
  "name": "recipes.grilled-silver-eel.name",
  "icon": "icons/commodities/biological/tail-rodent-orange.webp",
  "basicIngredients": 4,
  "specialIngredients": 1,
  "cookingLoreDC": 24,
  "survivalDC": 26,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.UMgvKT6nNTPvp28R",
  "level": 6,
  "cost": {
    "currency": "gp",
    "value": 13
  },
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Dj9026jn8dI7oP0j",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Vb39DIJ5OfWpN2ig",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Zw8I0G3RqDfNHuCl",
        "removeWhenPreparingCampsite": false,
        "grantsFreeAction": {
          "type": "freeAction",
          "name": "recipes.grilled-silver-eel.freeAction.name",
          "description": "recipes.grilled-silver-eel.freeAction.description",
          "durationSeconds": 60
        }
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.ta81jwzhkNsN88EZ",
        "removeWhenPreparingCampsite": false,
        "grantsFreeAction": {
          "type": "freeAction",
          "name": "recipes.grilled-silver-eel.freeAction.name",
          "description": "recipes.grilled-silver-eel.freeAction.description",
          "durationSeconds": 60
        }
      }
    ]
  }
}

=== endur4ever/pf2e-kingmaker-tools/data/recipes/Succulent Sausages.json
{
  "id": "succulent-sausages",
  "name": "recipes.succulent-sausages.name",
  "icon": "icons/consumables/food/sausage-bratwurst-mustard-red-yellow.webp",
  "basicIngredients": 3,
  "specialIngredients": 1,
  "cookingLoreDC": 18,
  "survivalDC": 20,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.IZoPx6QH5NRY1HBi",
  "level": 3,
  "cost": {
    "currency": "gp",
    "value": 3
  },
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.EULsp9VffKbWpD0b",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.G0qnixpCakGeHTp1",
        "removeAfterRest": true,
        "grantsReaction": {
          "type": "reaction",
          "name": "recipes.succulent-sausages.reaction.name",
          "description": "recipes.succulent-sausages.reaction.description"
        }
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.WDJQpYYx0N91mkO0",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.jseoPPvbPg4Vr7MI",
        "removeWhenPreparingCampsite": false,
        "grantsReaction": {
          "type": "reaction",
          "name": "recipes.succulent-sausages.reaction.name",
          "description": "recipes.succulent-sausages.reaction.description"
        }
      }
    ]
  }
}

=== endur4ever/pf2e-kingmaker-tools/data/recipes/Hearty Purple Soup.json
{
  "id": "hearty-purple-soup",
  "name": "recipes.hearty-purple-soup.name",
  "icon": "icons/tools/laboratory/mortar-liquid-pink.webp",
  "basicIngredients": 6,
  "specialIngredients": 3,
  "cookingLoreDC": 40,
  "survivalDC": 42,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.yAB0s5JgzCZpf0dT",
  "level": 16,
  "cost": {
    "currency": "gp",
    "value": 500
  },
  "rarity": "rare",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.6RjaP1s58ITIVn6u"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Zn0CB7bL7vHrMNTU"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.hLGCjXajAYEcII9J"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.o6F8QZbTvt9os8Ni",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.TQXXVzD1ZZHnouTI",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.SJvEGeMryIekwIKk",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "requirements": "legendary in Nature"
}

=== endur4ever/pf2e-kingmaker-tools/data/recipes/Black Linnorm Stew.json
{
  "id": "black-linnorm-stew",
  "name": "recipes.black-linnorm-stew.name",
  "icon": "icons/tools/cooking/bowl-steaming-brown.webp",
  "basicIngredients": 8,
  "specialIngredients": 3,
  "cookingLoreDC": 43,
  "survivalDC": 45,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.V6uIWe6BVFV9Ewo3",
  "level": 18,
  "cost": {
    "currency": "gp",
    "value": 1200
  },
  "rarity": "rare",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.I2LiwNjrowS5u4UG"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.m3FgRCWbVupkaORL"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.s1DfJpXFkJorHsuu",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.sxr0BsJJGeLyNBgq"
      }
    ]
  },
  "requirements": "legendary in Arcana or Nature"
}

=== endur4ever/pf2e-kingmaker-tools/data/recipes/Seasoned Wings And Thighs.json
{
  "id": "seasoned-wings-and-thighs",
  "name": "recipes.seasoned-wings-and-thighs.name",
  "icon": "icons/consumables/food/chicken-bird-cooked.webp",
  "basicIngredients": 4,
  "specialIngredients": 2,
  "cookingLoreDC": 30,
  "survivalDC": 32,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.BTKN1IgANoof0tfB",
  "level": 12,
  "cost": {
    "currency": "gp",
    "value": 100
  },
  "rarity": "uncommon",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.uchgkN3hm1T51zfM",
        "removeAfterRest": true
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw",
        "removeWhenPreparingCampsite": false,
        "grantsReaction": {
          "type": "reaction",
          "name": "recipes.seasoned-wings-and-thighs.reaction.name",
          "description": "recipes.seasoned-wings-and-thighs.reaction.description"
        }
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw",
        "grantsReaction": {
          "type": "reaction",
          "name": "recipes.seasoned-wings-and-thighs.reaction.name",
          "description": "recipes.seasoned-wings-and-thighs.reaction.description"
        }
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.q3vnRHRBn3HmRhkV",
        "removeAfterRest": true
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.xF0K40VzyjIbbRMA",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "requirements": "ability to cast fire spell"
}
